version: '3.8'
services:
  mongodb:
    image: mongo:7.0.0
    ports:
      - '27017:27017'
    networks:
      - fileshare
  
  fileshare-app:
    build: .
    image: fileshare
    environment:
      - MONGOSETTINGS__CONNECTIONSTRING=mongodb://mongodb:27017
      - MONGOSETTINGS__DATABASE=files
      - MAXFILESCOUNT=5
      - MAXFILESIZE=20971520
    ports:
      - 8080:80
    depends_on:
      - mongodb
    networks:
      - fileshare

networks:
  fileshare:
    external: false